<h3> Extração das informações e manipulação dos dados

In [191]:
import pandas as pd
import numpy as np

In [192]:
estabelecimentos = pd.read_excel('Lugares_atualizados.xlsx', sheet_name='Estabelecimentos', index_col=0)
estabelecimentos

Preco Estilo Musical Ambientacao/Movimentacao  \
Nome                                                                  
Sertanejo Sunset         60      Sertanejo                    Baixo   
MPB Lounge Garden       120            MPB                    Baixo   
Only Rock Bar            75           Rock                    Médio   
Sunrise Boat Party       70      Sertanejo                     Alto   
Soweto                  100         Pagode                     Alto   
Rock Under the Stars    130           Rock                     Alto   
Funk Night Fever         65           Funk                     Alto   
Funk Fusion Carnival     65           Funk                     Alto   

                      Horario Abertura  Horario Fechamento   Local  \
Nome                                                                 
Sertanejo Sunset                    14                  19   Oeste   
MPB Lounge Garden                   14                  19  Centro   
Only Rock Bar                       19                   2   Oeste   
Sunrise Boat Party                   8                  14     Sul   
Soweto                              14                  19  Centro   
Rock Under the Stars                18                   0   Oeste   
Funk Night Fever                    18                   0  Centro   
Funk Fusion Carnival                14                  19  Centro   

                      Acessibilidade - Cadeirantes  \
Nome                                                 
Sertanejo Sunset                                 1   
MPB Lounge Garden                                1   
Only Rock Bar                                    1   
Sunrise Boat Party                               0   
Soweto                                           1   
Rock Under the Stars                             1   
Funk Night Fever                                 0   
Funk Fusion Carnival                             0   

                      Acessibilidade - Surdo Mudo  Acessibilidade - Cego  \
Nome                                                                       
Sertanejo Sunset                                1                      0   
MPB Lounge Garden                               0                      1   
Only Rock Bar                                   0                      0   
Sunrise Boat Party                              0                      0   
Soweto                                          0                      0   
Rock Under the Stars                            1                      0   
Funk Night Fever                                0                      0   
Funk Fusion Carnival                            1                      0   

                      Acessibilidade - Nanismo  Open Bar  
Nome                                                      
Sertanejo Sunset                             0         0  
MPB Lounge Garden                            0         1  
Only Rock Bar                                0         0  
Sunrise Boat Party                           0         0  
Soweto                                       0         1  
Rock Under the Stars                         0         1  
Funk Night Fever                             0         0  
Funk Fusion Carnival                         0         1

In [193]:
for preco in estabelecimentos['Preco']:
    if preco >= 0.0 and preco <= 40.0:
        estabelecimentos['Preco'] = estabelecimentos['Preco'].replace(preco, 1)
    elif preco > 40.0 and preco <= 90.0:
        estabelecimentos['Preco'] = estabelecimentos['Preco'].replace(preco, 2)
    elif preco > 90.0 and preco <= 140.0:
        estabelecimentos['Preco'] = estabelecimentos['Preco'].replace(preco, 3)
    elif preco > 140.0 and preco <= 200.0:
        estabelecimentos['Preco'] = estabelecimentos['Preco'].replace(preco, 4)
    else:
        estabelecimentos['Preco'] = estabelecimentos['Preco'].replace(preco, 5)
        
estabelecimentos

Preco Estilo Musical Ambientacao/Movimentacao  \
Nome                                                                  
Sertanejo Sunset          2      Sertanejo                    Baixo   
MPB Lounge Garden         3            MPB                    Baixo   
Only Rock Bar             2           Rock                    Médio   
Sunrise Boat Party        2      Sertanejo                     Alto   
Soweto                    3         Pagode                     Alto   
Rock Under the Stars      3           Rock                     Alto   
Funk Night Fever          2           Funk                     Alto   
Funk Fusion Carnival      2           Funk                     Alto   

                      Horario Abertura  Horario Fechamento   Local  \
Nome                                                                 
Sertanejo Sunset                    14                  19   Oeste   
MPB Lounge Garden                   14                  19  Centro   
Only Rock Bar                       19                   2   Oeste   
Sunrise Boat Party                   8                  14     Sul   
Soweto                              14                  19  Centro   
Rock Under the Stars                18                   0   Oeste   
Funk Night Fever                    18                   0  Centro   
Funk Fusion Carnival                14                  19  Centro   

                      Acessibilidade - Cadeirantes  \
Nome                                                 
Sertanejo Sunset                                 1   
MPB Lounge Garden                                1   
Only Rock Bar                                    1   
Sunrise Boat Party                               0   
Soweto                                           1   
Rock Under the Stars                             1   
Funk Night Fever                                 0   
Funk Fusion Carnival                             0   

                      Acessibilidade - Surdo Mudo  Acessibilidade - Cego  \
Nome                                                                       
Sertanejo Sunset                                1                      0   
MPB Lounge Garden                               0                      1   
Only Rock Bar                                   0                      0   
Sunrise Boat Party                              0                      0   
Soweto                                          0                      0   
Rock Under the Stars                            1                      0   
Funk Night Fever                                0                      0   
Funk Fusion Carnival                            1                      0   

                      Acessibilidade - Nanismo  Open Bar  
Nome                                                      
Sertanejo Sunset                             0         0  
MPB Lounge Garden                            0         1  
Only Rock Bar                                0         0  
Sunrise Boat Party                           0         0  
Soweto                                       0         1  
Rock Under the Stars                         0         1  
Funk Night Fever                             0         0  
Funk Fusion Carnival                         0         1

In [194]:
clientes = pd.read_excel('Lugares_atualizados.xlsx', sheet_name='Clientes', index_col=0)
clientes.head()

Preco Estilo Musical Ambientacao/Movimentacao  Horario Abertura  \
Nome                                                                         
Cliente 1      2      Sertanejo                    Baixo                14   
Cliente 2      3            MPB                    Baixo                14   
Cliente 3      2           Rock                    Médio                19   
Cliente 4      3      Sertanejo                     Alto                 8   
Cliente 5      3         Pagode                     Alto                14   

           Horario Fechamento    Zona  Acessibilidade - Cadeirantes  \
Nome                                                                  
Cliente 1                  19   Oeste                             1   
Cliente 2                  19  Centro                             0   
Cliente 3                   2   Oeste                             1   
Cliente 4                  14     Sul                             0   
Cliente 5                  19   Oeste                             1   

           Acessibilidade - Surdo Mudo  Acessibilidade - Cego  \
Nome                                                            
Cliente 1                            1                      0   
Cliente 2                            0                      1   
Cliente 3                            0                      0   
Cliente 4                            0                      0   
Cliente 5                            0                      0   

           Acessibilidade - Nanismo  Open Bar  
Nome                                           
Cliente 1                         0         0  
Cliente 2                         0         1  
Cliente 3                         0         0  
Cliente 4                         0         0  
Cliente 5                         0         1

In [195]:
price = pd.read_excel('Lugares_atualizados.xlsx', sheet_name='Range_Preços')
price.head()

Legenda
0     1 - 0 á 40
1    2 - 40 á 90
2   3 - 90 á 140
3  4 - 140 á 200
4       5 - 200+

<h3> Vetorização dos estabelecimentos

In [196]:
from sklearn.feature_extraction import DictVectorizer

dv_1 = DictVectorizer(sparse=False)
dv_estabelecimentos = dv_1.fit_transform(estabelecimentos.apply(dict, 1))

print(dv_estabelecimentos)

[[ 1.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1. 14. 19.  0.  1.  0.  0.
   2.]
 [ 1.  1.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0. 14. 19.  1.  0.  0.  1.
   3.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0. 19.  2.  0.  1.  0.  0.
   2.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  8. 14.  0.  0.  1.  0.
   2.]
 [ 1.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0. 14. 19.  1.  0.  0.  1.
   3.]
 [ 1.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0. 18.  0.  0.  1.  0.  1.
   3.]
 [ 0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0. 18.  0.  1.  0.  0.  0.
   2.]
 [ 0.  0.  0.  1.  1.  0.  0.  1.  0.  0.  0.  0. 14. 19.  1.  0.  0.  1.
   2.]]


In [197]:
df_estabelecimentos = pd.DataFrame(dv_estabelecimentos, columns=dv_1.get_feature_names_out())
df_estabelecimentos.head()

Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                           1.0                    0.0   
1                           1.0                    1.0   
2                           1.0                    0.0   
3                           0.0                    0.0   
4                           1.0                    0.0   

   Acessibilidade - Nanismo  Acessibilidade - Surdo Mudo  \
0                       0.0                          1.0   
1                       0.0                          0.0   
2                       0.0                          0.0   
3                       0.0                          0.0   
4                       0.0                          0.0   

   Ambientacao/Movimentacao=Alto  Ambientacao/Movimentacao=Baixo  \
0                            0.0                             1.0   
1                            0.0                             1.0   
2                            0.0                             0.0   
3                            1.0                             0.0   
4                            1.0                             0.0   

   Ambientacao/Movimentacao=Médio  Estilo Musical=Funk  Estilo Musical=MPB  \
0                             0.0                  0.0                 0.0   
1                             0.0                  0.0                 1.0   
2                             1.0                  0.0                 0.0   
3                             0.0                  0.0                 0.0   
4                             0.0                  0.0                 0.0   

   Estilo Musical=Pagode  Estilo Musical=Rock  Estilo Musical=Sertanejo  \
0                    0.0                  0.0                       1.0   
1                    0.0                  0.0                       0.0   
2                    0.0                  1.0                       0.0   
3                    0.0                  0.0                       1.0   
4                    1.0                  0.0                       0.0   

   Horario Abertura  Horario Fechamento  Local=Centro  Local=Oeste  Local=Sul  \
0              14.0                19.0           0.0          1.0        0.0   
1              14.0                19.0           1.0          0.0        0.0   
2              19.0                 2.0           0.0          1.0        0.0   
3               8.0                14.0           0.0          0.0        1.0   
4              14.0                19.0           1.0          0.0        0.0   

   Open Bar  Preco  
0       0.0    2.0  
1       1.0    3.0  
2       0.0    2.0  
3       0.0    2.0  
4       1.0    3.0

<h3> Vetorização dos clientes

In [198]:
dv_2 = DictVectorizer(sparse=False)
dv_clientes = dv_2.fit_transform(clientes.apply(dict, 1))

print(dv_clientes)

[[1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 1. 0.]]


In [199]:
df_clientes = pd.DataFrame(dv_clientes, columns=dv_2.get_feature_names_out())
df_clientes.head()

Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                           1.0                    0.0   
1                           0.0                    1.0   
2                           1.0                    0.0   
3                           0.0                    0.0   
4                           1.0                    0.0   

   Acessibilidade - Nanismo  Acessibilidade - Surdo Mudo  \
0                       0.0                          1.0   
1                       0.0                          0.0   
2                       0.0                          0.0   
3                       0.0                          0.0   
4                       0.0                          0.0   

   Ambientacao/Movimentacao=Alto  Ambientacao/Movimentacao=Baixo  \
0                            0.0                             1.0   
1                            0.0                             1.0   
2                            0.0                             0.0   
3                            1.0                             0.0   
4                            1.0                             0.0   

   Ambientacao/Movimentacao=Médio  Estilo Musical=Eletrônica  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             1.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   

   Estilo Musical=Forró  Estilo Musical=Funk  ...  Estilo Musical=funk  \
0                   0.0                  0.0  ...                  0.0   
1                   0.0                  0.0  ...                  0.0   
2                   0.0                  0.0  ...                  0.0   
3                   0.0                  0.0  ...                  0.0   
4                   0.0                  0.0  ...                  0.0   

   Horario Abertura  Horario Fechamento  Open Bar  Preco  Zona=Centro  \
0              14.0                19.0       0.0    2.0          0.0   
1              14.0                19.0       1.0    3.0          1.0   
2              19.0                 2.0       0.0    2.0          0.0   
3               8.0                14.0       0.0    3.0          0.0   
4              14.0                19.0       1.0    3.0          0.0   

   Zona=Leste  Zona=Norte  Zona=Oeste  Zona=Sul  
0         0.0         0.0         1.0       0.0  
1         0.0         0.0         0.0       0.0  
2         0.0         0.0         1.0       0.0  
3         0.0         0.0         0.0       1.0  
4         0.0         0.0         1.0       0.0  

[5 rows x 31 columns]

<h3> Agrupamento de colunas da tabela de estabelecimentos

In [200]:
from sklearn.decomposition import PCA

estilo_columns = [col for col in df_estabelecimentos.columns if 'Estilo Musical' in col]

df_estilo = df_estabelecimentos[estilo_columns]

pca = PCA(n_components=1)

pca.fit(df_estilo)

df_estilo_compact = pca.transform(df_estilo)

df_estabelecimentos['estilo_compact'] = df_estilo_compact

df_estabelecimentos = df_estabelecimentos.drop(estilo_columns, axis=1)

print(df_estabelecimentos)

   Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                           1.0                    0.0   
1                           1.0                    1.0   
2                           1.0                    0.0   
3                           0.0                    0.0   
4                           1.0                    0.0   
5                           1.0                    0.0   
6                           0.0                    0.0   
7                           0.0                    0.0   

   Acessibilidade - Nanismo  Acessibilidade - Surdo Mudo  \
0                       0.0                          1.0   
1                       0.0                          0.0   
2                       0.0                          0.0   
3                       0.0                          0.0   
4                       0.0                          0.0   
5                       0.0                          1.0   
6                       0.0                          0.0 

In [201]:
local_columns = [col for col in df_estabelecimentos.columns if 'Local' in col]

df_local = df_estabelecimentos[local_columns]

pca = PCA(n_components=1)

pca.fit(df_local)

df_local_compact = pca.transform(df_local)

df_estabelecimentos['local_compact'] = df_local_compact

df_estabelecimentos = df_estabelecimentos.drop(local_columns, axis=1)

print(df_estabelecimentos)

   Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                           1.0                    0.0   
1                           1.0                    1.0   
2                           1.0                    0.0   
3                           0.0                    0.0   
4                           1.0                    0.0   
5                           1.0                    0.0   
6                           0.0                    0.0   
7                           0.0                    0.0   

   Acessibilidade - Nanismo  Acessibilidade - Surdo Mudo  \
0                       0.0                          1.0   
1                       0.0                          0.0   
2                       0.0                          0.0   
3                       0.0                          0.0   
4                       0.0                          0.0   
5                       0.0                          1.0   
6                       0.0                          0.0 

<h3> Agrupamento de colunas da tabela de clientes

In [202]:
estilo_columns = [col for col in df_clientes.columns if 'Estilo Musical' in col]

df_estilo = df_clientes[estilo_columns]

pca = PCA(n_components=1)

pca.fit(df_estilo)

df_estilo_compact = pca.transform(df_estilo)

df_clientes['estilo_compact'] = df_estilo_compact

df_clientes = df_clientes.drop(estilo_columns, axis=1)

print(df_clientes)

    Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                            1.0                    0.0   
1                            0.0                    1.0   
2                            1.0                    0.0   
3                            0.0                    0.0   
4                            1.0                    0.0   
5                            1.0                    0.0   
6                            0.0                    0.0   
7                            0.0                    0.0   
8                            0.0                    0.0   
9                            0.0                    0.0   
10                           0.0                    0.0   
11                           1.0                    0.0   
12                           1.0                    0.0   
13                           0.0                    0.0   
14                           1.0                    1.0   
15                           0.0                    1.0 

In [203]:
zona_columns = [col for col in df_clientes.columns if 'Zona' in col]

# Create a subset of the dataframe with only the estilo_columns
df_zona = df_clientes[zona_columns]

# Create the PCA model
pca = PCA(n_components=1)

# Fit the PCA model to the estilo_columns
pca.fit(df_zona)

# Transform the estilo_columns using the PCA model
df_zona_compact = pca.transform(df_zona)

# Add the compacted columns to the original dataframe
df_clientes['local_compact'] = df_zona_compact

# Drop the estilo_columns from the dataframe
df_clientes = df_clientes.drop(zona_columns, axis=1)

# Print the updated dataframe
print(df_clientes)

    Acessibilidade - Cadeirantes  Acessibilidade - Cego  \
0                            1.0                    0.0   
1                            0.0                    1.0   
2                            1.0                    0.0   
3                            0.0                    0.0   
4                            1.0                    0.0   
5                            1.0                    0.0   
6                            0.0                    0.0   
7                            0.0                    0.0   
8                            0.0                    0.0   
9                            0.0                    0.0   
10                           0.0                    0.0   
11                           1.0                    0.0   
12                           1.0                    0.0   
13                           0.0                    0.0   
14                           1.0                    1.0   
15                           0.0                    1.0 

<h3> Cálculo das similaridades entre os cossenos

In [204]:
from sklearn.metrics.pairwise import cosine_similarity
similarities = []

for index, row in df_clientes.iterrows():
    row_similarities = []
    for _, estabelecimento_row in df_estabelecimentos.iterrows():
        cos_sim = cosine_similarity([row.values], [estabelecimento_row.values])
        row_similarities.append(cos_sim[0][0])
    similarities.append(row_similarities)

similarities

[[0.9998833139837919,
  0.9947894032050971,
  0.6748044440142469,
  0.9874774671280331,
  0.9938989376101687,
  0.5957758090586126,
  0.5925644216416245,
  0.9947488901733953],
 [0.9941466222885699,
  0.9990204247479231,
  0.673164471493684,
  0.9877560386204609,
  0.9963838287295992,
  0.5967735884751102,
  0.5963145120490799,
  0.9954941128696756],
 [0.6756056682103289,
  0.6746170863720988,
  0.9993216355289798,
  0.5861679259479912,
  0.6752092282985119,
  0.9862898698326835,
  0.9877952610112396,
  0.6716419807485471],
 [0.981428627539789,
  0.9861962225577133,
  0.5838472903443913,
  0.9967925205762975,
  0.9896097547576665,
  0.5066946527301561,
  0.507180771143297,
  0.9863061212844982],
 [0.9955459017495576,
  0.9955965155895543,
  0.6759521433687026,
  0.9909735220953344,
  0.9982261339065579,
  0.6020389093953767,
  0.5968356001069772,
  0.995584083168225],
 [0.5950621578421835,
  0.599040714854441,
  0.9818840314711008,
  0.5062076424189375,
  0.6018243434555682,
  0.997839

In [205]:
i = 0
melhor_escolha = []

for vetor in similarities:
   min = np.argmin(vetor)
   melhor_escolha.append(min)
   i += 1

print(melhor_escolha)

[6, 6, 3, 5, 6, 3, 3, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 6, 3, 3, 3, 5, 3, 5, 3, 3, 3, 3, 5, 3, 3, 3]


<h3> Indicação de estabelecimento para cada cliente

In [206]:
estabelecimentos_finais = pd.read_excel('Lugares_atualizados.xlsx', sheet_name='Estabelecimentos')
estabelecimentos_finais

Nome  Preco Estilo Musical Ambientacao/Movimentacao  \
0      Sertanejo Sunset     60      Sertanejo                    Baixo   
1    MPB Lounge Garden     120            MPB                    Baixo   
2         Only Rock Bar     75           Rock                    Médio   
3   Sunrise Boat Party      70      Sertanejo                     Alto   
4                Soweto    100         Pagode                     Alto   
5  Rock Under the Stars    130           Rock                     Alto   
6      Funk Night Fever     65           Funk                     Alto   
7  Funk Fusion Carnival     65           Funk                     Alto   

   Horario Abertura  Horario Fechamento   Local  Acessibilidade - Cadeirantes  \
0                14                  19   Oeste                             1   
1                14                  19  Centro                             1   
2                19                   2   Oeste                             1   
3                 8                  14     Sul                             0   
4                14                  19  Centro                             1   
5                18                   0   Oeste                             1   
6                18                   0  Centro                             0   
7                14                  19  Centro                             0   

   Acessibilidade - Surdo Mudo  Acessibilidade - Cego  \
0                            1                      0   
1                            0                      1   
2                            0                      0   
3                            0                      0   
4                            0                      0   
5                            1                      0   
6                            0                      0   
7                            1                      0   

   Acessibilidade - Nanismo  Open Bar  
0                         0         0  
1                         0         1  
2                         0         0  
3                         0         0  
4                         0         1  
5                         0         1  
6                         0         0  
7                         0         1

In [207]:
i = 1

for index in melhor_escolha:
    print(f'O estabelecimento mais adequado para o cliente {i} é: \n{estabelecimentos_finais.iloc[index]}')
    i += 1

O estabelecimento mais adequado para o cliente 1 é: 
Nome                            Funk Night Fever
Preco                                         65
Estilo Musical                              Funk
Ambientacao/Movimentacao                    Alto
Horario Abertura                              18
Horario Fechamento                             0
Local                                     Centro
Acessibilidade - Cadeirantes                   0
Acessibilidade - Surdo Mudo                    0
Acessibilidade - Cego                          0
Acessibilidade - Nanismo                       0
Open Bar                                       0
Name: 6, dtype: object
O estabelecimento mais adequado para o cliente 2 é: 
Nome                            Funk Night Fever
Preco                                         65
Estilo Musical                              Funk
Ambientacao/Movimentacao                    Alto
Horario Abertura                              18
Horario Fechamento                    